version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: spring_postgres
    restart: always
    volumes:
      - "spring_postgresql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5432:5432"

volumes:
  spring_postgresql_data:
